//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="UpdaterServiceSoap", Namespace="http://tempuri.org/")]
public partial class UpdaterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback UpdateOperationCompleted;
    
    /// <remarks/>
    public UpdaterService() {
        this.Url = "http://adam.stream57.local/new.asmx";
    }
    
    /// <remarks/>
    public UpdaterService(string url) {
        this.Url = url;
    }
    
    /// <remarks/>
    public event UpdateCompletedEventHandler UpdateCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void Update(string appName, string appData, bool bSuccess) {
        this.Invoke("Update", new object[] {
                    appName,
                    appData,
                    bSuccess});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate(string appName, string appData, bool bSuccess, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update", new object[] {
                    appName,
                    appData,
                    bSuccess}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdate(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateAsync(string appName, string appData, bool bSuccess) {
        this.UpdateAsync(appName, appData, bSuccess, null);
    }
    
    /// <remarks/>
    public void UpdateAsync(string appName, string appData, bool bSuccess, object userState) {
        if ((this.UpdateOperationCompleted == null)) {
            this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
        }
        this.InvokeAsync("Update", new object[] {
                    appName,
                    appData,
                    bSuccess}, this.UpdateOperationCompleted, userState);
    }
    
    private void OnUpdateOperationCompleted(object arg) {
        if ((this.UpdateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void UpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
